import numpy as np
import matplotlib.pyplot as plt
import sympy as sm

"""Jill designs solar panels as a hobby.

On April 1st, Jill's "Mark I" design begins generating power: 1 kJ/day.

On May 1st, her “Mark II” design begins generating 4 kJ of power per day.

1. What day is it when Jill's Mark II design has generated as much total energy as the Mark I design?

2. How much total energy have both generated by that day?

3. What would the solutions to (1.) and (2). be if Mark II design generated 1kJ of power per day?"""

t = np.linspace(0,365,1000)

E1 = 1*t
E2 = 4*(t-30)

fig,ax = plt.subplots()
d = sm.symbols('d')

equection = sm.Eq(d, 4*(d-30))
solution = sm.solve(equection,d)
print(solution)

ax.plot(t,E1,'r')
ax.plot(t,E2,'b')
ax.grid(True)

plt.xlim(0,60)
plt.ylim(0,200)
plt.title('Time-energy')
plt.xlabel('time(days)')
plt.ylabel('energy(kJ)')
plt.axhline(y=solution[0],color='green',linestyle='--')
plt.axvline(x=solution[0],color='green',linestyle='--')
plt.show()
